---
title: "Plant_1_CART_Period"
author: "tanchuanxin"
date: "11/1/2021"
output: html_document
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE)
library(data.table)
library(rpart)
library(rpart.plot)
library(car)
library(corrplot)
library(tidyverse)
library(caTools)



# setwd("C:/Users/matth/Desktop/Course Materials for Stu/AY21 Team Assignment and Project") 
setwd("C:/Users/user/Documents/Github/project-MAI") # chuanxin's wd
set.seed(2021)
seed = 2021

# load dataset
plant_1.dt <- fread("Plant_1_Data.csv")

# convert some features into factors where relevant
plant_1.dt$SOURCE_KEY <- factor(plant_1.dt$SOURCE_KEY)
plant_1.dt$DOTW <- factor(plant_1.dt$DOTW)
plant_1.dt$TIME <- factor(plant_1.dt$TIME)
plant_1.dt$DATE <- factor(plant_1.dt$DATE)

```




```{r cleaning}
# remove some of the extra features that we have
cart_period_yield.dt <- subset(plant_1.dt, select = -c(DATE, PLANT_ID, DOTW, DATE_TIME, DAILY_YIELD, TOTAL_YIELD, DC_POWER, AC_POWER))


summary(cart_period_yield.dt)
```



``` {r cart}
# cart.dt <- select(cart_period_yield.dt, c(PERIOD_YIELD, AMBIENT_TEMPERATURE, IRRADIATION, 'Wind speed (m/s)'))

cart.dt <- subset(cart_period_yield.dt, select = -c(SOURCE_KEY))


cart1 <- rpart(PERIOD_YIELD ~ ., data = cart.dt, method = 'anova', control = rpart.control(minsplit = 2, cp = 0))
# printcp(cart1, digits = 3)
plotcp(cart1)

# min cp + 1 stddev
CVerror.cap <- cart1$cptable[which.min(cart1$cptable[,"xerror"]), "xerror"] +  cart1$cptable[which.min(cart1$cptable[,"xerror"]), "xstd"]

# Find the optimal CP region whose CV error is just below CVerror.cap in maximal tree cart1.
i <- 1; j<- 4
while (cart1$cptable[i,j] > CVerror.cap) {
  i <- i + 1
}
cp1 = ifelse(i > 1, sqrt(cart1$cptable[i,1] * cart1$cptable[i-1,1]), 1)

cart2 <- prune(cart1, cp = cp1)
printcp(cart2, digits = 3)

# Root node error: 3.21e+08/33294 = 9634
# cart2 trainset MSE = 0.0231 * 9634 = 223
# cart2 CV MSE = 0.0253 * 9634 = 244

rpart.plot(cart2, nn = T, main = "Optimal Tree")
## The number inside each node represent the mean value of Y.

cart2$variable.importance
```

<h1>Too deep!</h1>
We need to truncate the tree even more, the optimal tree cannot be interpreted even though it is optimal

``` {r cart_truncated}
# inspecting the cptable, we believe that 0.055 xerror will give a tree that can be interpreted
CVerror.cap <- 0.055

# Find the optimal CP region whose CV error is just below CVerror.cap in maximal tree cart1.
i <- 1; j<- 4
while (cart1$cptable[i,j] > CVerror.cap) {
  i <- i + 1
}
cp2 = ifelse(i > 1, sqrt(cart1$cptable[i,1] * cart1$cptable[i-1,1]), 1)

cart3 <- prune(cart1, cp = cp2)
printcp(cart3, digits = 3)

# Root node error: 3.21e+08/33294 = 9634
# cart2 trainset MSE = 0.0637 * 9634 = 614
# cart2 CV MSE = 0.0639 * 9634 = 616

rpart.plot(cart3, nn = T, main = "Truncated Tree", tweak=1.7)
## The number inside each node represent the mean value of Y.

cart3$variable.importance
```



